# Generated by Django 5.2.8 on 2026-08-29 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_number', models.CharField(max_length=50, unique=True)),
                ('organisation', models.CharField(choices=[('ODPP', 'Office of the Director of Public Prosecutions'), ('UGANDA_POLICE', 'Uganda Police Force')], max_length=24)),
                ('role', models.CharField(choices=[('INVESTIGATING_OFFICER', 'Investigating Officer'), ('STATION_SUPERVISOR', 'Station Supervisor'), ('POLICE_LIAISON', 'Police Liaison'), ('REGISTRY_CLERK', 'Registry Clerk'), ('REGISTRY_OFFICER', 'Registry Officer'), ('RESIDENT_STATE_ATTORNEY', 'Resident State Attorney'), ('REGIONAL_INSPECTORATE', 'Regional Inspectorate Officer'), ('HEAD_OF_COMPLAINTS', 'Head of Complaints'), ('INTERNAL_AFFAIRS', 'Internal Affairs Officer'), ('DPP', 'Director of Public Prosecutions'), ('DEPUTY_DPP', 'Deputy Director of Public Prosecutions'), ('DIRECTORATE_HEAD', 'Directorate Head')], max_length=32)),
                ('work_phone', models.CharField(blank=True, max_length=32)),
                ('job_title', models.CharField(max_length=120)),
                ('rank', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
                ('current_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_staff', to='common.office')),
            ],
            options={
                'ordering': ['account__last_name', 'account__first_name', 'officer_number'],
            },
        ),
        migrations.CreateModel(
            name='StaffPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=120)),
                ('rank', models.CharField(blank=True, max_length=80)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('reason', models.CharField(max_length=240)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_postings', to='common.office')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_postings', to=settings.AUTH_USER_MODEL)),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_reports', to='staff.staffprofile')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-effective_from', 'staff_member__officer_number'],
            },
        ),
        migrations.CreateModel(
            name='StaffScopeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_level', models.CharField(choices=[('NATIONAL', 'National'), ('REGION', 'Region'), ('OFFICE', 'Office')], max_length=16)),
                ('assigned_from', models.DateField()),
                ('assigned_until', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(max_length=240)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_staff_scopes', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scope_assignments', to='common.office')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scope_assignments', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-assigned_from', 'staff_member__officer_number'],
            },
        ),
    ]
