# Generated by Django 5.2.8 on 2026-08-29 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('documents', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('complaint_context', models.CharField(max_length=500)),
                ('stage', models.CharField(choices=[('POLICE_OPENED', 'Police opened'), ('POLICE_PREPARING', 'Police preparing'), ('DISPATCHED_TO_ODPP', 'Dispatched to ODPP'), ('ODPP_RECEIVED', 'ODPP received'), ('UNDER_PERUSAL', 'Under perusal'), ('DFI_ISSUED', 'DFI issued'), ('SANCTIONED', 'Sanctioned'), ('BEFORE_COURT', 'Before court'), ('CLOSED', 'Closed')], default='POLICE_OPENED', max_length=24)),
                ('sensitivity', models.CharField(choices=[('STANDARD', 'Standard'), ('RESTRICTED', 'Restricted'), ('CONFIDENTIAL', 'Confidential')], default='STANDARD', max_length=16)),
                ('opened_on', models.DateField()),
                ('expected_action_on', models.DateField(blank=True, null=True)),
                ('last_meaningful_update_at', models.DateTimeField()),
                ('is_demo', models.BooleanField(default=False)),
                ('allocated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocated_cases', to='staff.staffprofile')),
                ('current_custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='held_cases', to='staff.staffprofile')),
                ('current_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='held_cases', to='common.office')),
                ('originating_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originated_cases', to='common.office')),
                ('responsible_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='common.region')),
            ],
            options={
                'ordering': ['-last_meaningful_update_at', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='CaseMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('DISPATCH', 'Dispatch'), ('RECEIPT', 'Receipt'), ('INTERNAL_TRANSFER', 'Internal transfer'), ('RETURN_FOR_ACTION', 'Return for action'), ('COURT_TRANSFER', 'Court transfer'), ('ARCHIVAL', 'Closure / archival')], max_length=20)),
                ('moved_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('declared_contents', models.CharField(max_length=300)),
                ('receipt_acknowledged', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='cases.casemovement')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_case_movements', to='staff.staffprofile')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_case_movements', to='staff.staffprofile')),
                ('sent_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_case_movements', to='common.office')),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_case_movements', to='common.office')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='cases.casereference')),
            ],
            options={
                'ordering': ['moved_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CaseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=300)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_cases', to='staff.staffprofile')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_assignments', to='staff.staffprofile')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='cases.casereference')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('SD_OB', 'Station diary / occurrence book'), ('CRB', 'Crime report book'), ('ODPP', 'ODPP reference'), ('COURT', 'Court reference')], max_length=12)),
                ('value', models.CharField(max_length=100)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('issuing_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_case_identifiers', to='common.office')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_case_identifiers', to='staff.staffprofile')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='cases.casereference')),
            ],
            options={
                'ordering': ['reference_type', 'value'],
                'constraints': [models.UniqueConstraint(fields=('reference_type', 'value'), name='unique_case_identifier_value')],
            },
        ),
        migrations.CreateModel(
            name='CaseDocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(max_length=240)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_links', to='documents.document')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_case_documents', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_links', to='cases.casereference')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('case', 'document'), name='unique_case_document_link')],
            },
        ),
    ]
