# Generated by Django 5.2.8 on 2026-08-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_casecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereference',
            name='judgement_outcome',
            field=models.CharField(blank=True, choices=[('CONVICTED', 'Convicted'), ('ACQUITTED', 'Acquitted'), ('DISCHARGED', 'Discharged'), ('WITHDRAWN', 'Withdrawn'), ('OTHER', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='casereference',
            name='stage',
            field=models.CharField(choices=[('POLICE_OPENED', 'Police opened'), ('POLICE_PREPARING', 'Police preparing'), ('DISPATCHED_TO_ODPP', 'Dispatched to ODPP'), ('ODPP_RECEIVED', 'ODPP received'), ('UNDER_PERUSAL', 'Under perusal'), ('DFI_ISSUED', 'DFI issued'), ('SANCTIONED', 'Sanctioned'), ('BEFORE_COURT', 'Before court'), ('HEARING', 'Hearing / trial'), ('JUDGEMENT_DELIVERED', 'Judgement delivered'), ('CLOSED', 'Closed')], default='POLICE_OPENED', max_length=24),
        ),
    ]
