# Generated by Django 5.2.8 on 2026-08-31 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_casereference_judgement_outcome_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COMPLAINANT', 'Victim / complainant'), ('ACCUSED', 'Accused / defendant'), ('NEXT_OF_KIN', 'Next of kin'), ('WITNESS', 'Witness / informant'), ('COUNSEL', 'Legal representative')], max_length=16)),
                ('full_name', models.CharField(max_length=160)),
                ('nin', models.CharField(max_length=14, verbose_name='NIN')),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='cases.casereference')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_case_parties', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['case_id', 'role', 'full_name'],
                'constraints': [models.UniqueConstraint(fields=('case', 'nin'), name='unique_case_party_nin')],
            },
        ),
    ]
