# Generated by Django 5.2.8 on 2026-08-29 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('office_type', models.CharField(choices=[('HEADQUARTERS', 'Headquarters'), ('REGIONAL_DPP', 'Regional DPP Office'), ('POLICE_STATION', 'Police Station'), ('REGISTRY', 'Registry'), ('DIRECTORATE', 'Directorate'), ('DEPARTMENT', 'Department')], max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_offices', to='common.office')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='common.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
