# Generated by Django 5.2.8 on 2026-08-29 03:52

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('file_size', models.PositiveBigIntegerField()),
                ('content_hash', models.CharField(max_length=128, unique=True)),
                ('category', models.CharField(choices=[('COMPLAINT_EVIDENCE', 'Complaint evidence'), ('CORRESPONDENCE', 'Correspondence'), ('REVIEW_NOTE', 'Review note'), ('DETERMINATION', 'Determination'), ('COMMUNICATION_PROOF', 'Communication proof'), ('FORM', 'Form')], max_length=32)),
                ('visibility', models.CharField(choices=[('INTERNAL', 'Internal'), ('RESTRICTED', 'Restricted'), ('CONFIDENTIAL', 'Confidential')], default='RESTRICTED', max_length=16)),
                ('processing_status', models.CharField(choices=[('QUEUED', 'Queued'), ('SCANNING', 'Scanning'), ('INDEXED', 'Indexed'), ('FAILED', 'Failed'), ('QUARANTINED', 'Quarantined')], default='QUEUED', max_length=16)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('ocr_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('requires_manual_verification', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(editable=False, max_length=160)),
                ('author_officer_number', models.CharField(blank=True, editable=False, max_length=50)),
                ('author_role', models.CharField(blank=True, editable=False, max_length=32)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_comments', to=settings.AUTH_USER_MODEL)),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='documents.documentcomment')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='documents.document')),
                ('supporting_documents', models.ManyToManyField(blank=True, related_name='attached_to_comments', to='documents.document')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentProcessingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SCANNING', 'Scanning'), ('INDEXED', 'Indexed'), ('FAILED', 'Failed'), ('QUARANTINED', 'Quarantined')], max_length=16)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_attempts', to='documents.document')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_processing_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
