# Generated by Django 5.2.8 on 2026-08-29 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConductComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('source_complaint_reference', models.CharField(blank=True, help_text='The public complaint reference this was escalated from, if any.', max_length=32)),
                ('subject_officer_id', models.PositiveIntegerField()),
                ('subject_officer_name', models.CharField(max_length=160)),
                ('subject_officer_number', models.CharField(max_length=50)),
                ('subject_officer_role', models.CharField(max_length=32)),
                ('subject_officer_office', models.CharField(blank=True, max_length=160)),
                ('complainant_name', models.CharField(max_length=160)),
                ('complainant_nin', models.CharField(blank=True, max_length=14)),
                ('complainant_phone', models.CharField(blank=True, max_length=32)),
                ('complainant_email', models.EmailField(blank=True, max_length=254)),
                ('allegation_category', models.CharField(choices=[('ABUSE_OF_OFFICE', 'Abuse of office'), ('BRIBERY_CORRUPTION', 'Bribery or corruption'), ('EVIDENCE_TAMPERING', 'Evidence tampering'), ('UNPROFESSIONAL_CONDUCT', 'Unprofessional conduct'), ('DELAY_OR_NEGLECT', 'Delay or neglect of duty'), ('HARASSMENT', 'Harassment or intimidation'), ('OTHER', 'Other misconduct')], max_length=32)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('narrative', models.TextField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('UNDER_INQUIRY', 'Under inquiry'), ('REFERRED_TO_DISCIPLINE', 'Referred to disciplinary process'), ('SUBSTANTIATED', 'Substantiated'), ('NOT_SUBSTANTIATED', 'Not substantiated'), ('WITHDRAWN', 'Withdrawn'), ('CLOSED', 'Closed')], default='RECEIVED', max_length=28)),
                ('assigned_investigator_id', models.PositiveIntegerField(blank=True, null=True)),
                ('assigned_investigator_name', models.CharField(blank=True, max_length=160)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('last_meaningful_update_at', models.DateTimeField(auto_now_add=True)),
                ('is_demo', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-last_meaningful_update_at', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='ConductSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ConductDetermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding', models.CharField(choices=[('SUBSTANTIATED', 'Substantiated'), ('NOT_SUBSTANTIATED', 'Not substantiated'), ('PARTIALLY_SUBSTANTIATED', 'Partially substantiated'), ('INCONCLUSIVE', 'Inconclusive')], max_length=28)),
                ('recommended_action', models.CharField(choices=[('NO_ACTION', 'No further action'), ('REPRIMAND', 'Reprimand'), ('SUSPENSION', 'Suspension'), ('DISMISSAL', 'Dismissal'), ('REFERRED_TO_PROSECUTION', 'Referred for prosecution'), ('OTHER', 'Other')], max_length=28)),
                ('notes', models.TextField(blank=True)),
                ('determined_by_id', models.PositiveIntegerField()),
                ('determined_by_name', models.CharField(max_length=160)),
                ('determined_at', models.DateTimeField(auto_now_add=True)),
                ('conduct_complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='determinations', to='conduct.conductcomplaint')),
            ],
            options={
                'ordering': ['-determined_at'],
            },
        ),
        migrations.CreateModel(
            name='ConductEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('RECEIVED', 'Received'), ('ASSIGNED', 'Investigator assigned'), ('REASSIGNED', 'Investigator reassigned'), ('STATUS_CHANGED', 'Status changed'), ('COMMENT', 'Comment added'), ('DETERMINATION', 'Determination recorded')], max_length=20)),
                ('actor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('actor_name', models.CharField(blank=True, max_length=160)),
                ('detail', models.CharField(max_length=700)),
                ('previous_status', models.CharField(blank=True, max_length=28)),
                ('resulting_status', models.CharField(blank=True, max_length=28)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('conduct_complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='conduct.conductcomplaint')),
            ],
            options={
                'ordering': ['occurred_at', 'pk'],
            },
        ),
    ]
