# Generated by Django 5.2.8 on 2026-08-29 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('common', '0001_initial'),
        ('documents', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('tracking_pin_hash', models.CharField(editable=False, max_length=256)),
                ('qr_locator_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('intake_channel', models.CharField(choices=[('PUBLIC_PORTAL', 'Public portal'), ('CALL_CENTRE', 'Toll-free / call centre'), ('ASSISTED_DESK', 'Walk-in / assisted desk'), ('MONITORED_EMAIL', 'Monitored email')], max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source_evidence_reference', models.CharField(blank=True, max_length=160)),
                ('complainant_name', models.CharField(max_length=160)),
                ('complainant_phone', models.CharField(blank=True, max_length=32)),
                ('complainant_email', models.EmailField(blank=True, max_length=254)),
                ('preferred_contact_channel', models.CharField(blank=True, max_length=20)),
                ('supplied_case_reference', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=240)),
                ('narrative', models.TextField()),
                ('classification', models.CharField(choices=[('UNCLASSIFIED', 'Awaiting classification'), ('TYPE_B', 'Type B - process complaint'), ('TYPE_A_HANDOFF', 'Type A - transferred to conduct')], default='UNCLASSIFIED', max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('OPEN_RSA', 'Open with responsible officer'), ('RESOLVED_RSA', 'Resolved by responsible officer'), ('ESCALATED_REGIONAL', 'Escalated to regional review'), ('RESOLVED_REGIONAL', 'Resolved by regional review'), ('ESCALATED_HQ', 'Escalated to headquarters'), ('REINSTATED', 'Reinstated by directive'), ('SANCTIONED', 'Sanctioned by directive'), ('WITHDRAWN', 'Withdrawn'), ('REFERRED_OUT', 'Referred out'), ('TYPE_A_HANDOFF', 'Transferred to Internal Affairs')], default='RECEIVED', max_length=24)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('last_meaningful_update_at', models.DateTimeField(auto_now_add=True)),
                ('public_status', models.CharField(default='Your complaint has been received and is awaiting review.', max_length=240)),
                ('type_a_handoff_reference', models.CharField(blank=True, editable=False, max_length=32)),
                ('is_demo', models.BooleanField(default=False)),
                ('assigned_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_complaints', to='common.office')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_complaints', to='staff.staffprofile')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='captured_complaints', to=settings.AUTH_USER_MODEL)),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='cases.casereference')),
            ],
            options={
                'ordering': ['-last_meaningful_update_at', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=300)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')])),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_complaint_history', to='staff.staffprofile')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_assignment_history', to='staff.staffprofile')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='complaints.complaint')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('LETTER', 'Letter'), ('IN_PERSON', 'In person')], max_length=16)),
                ('recipient', models.CharField(max_length=180)),
                ('outcome', models.CharField(max_length=500)),
                ('communicated_at', models.DateTimeField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communications', to='complaints.complaint')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_communications', to='staff.staffprofile')),
                ('supporting_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_records', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintDetermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding', models.CharField(choices=[('UPHELD', 'Complaint upheld'), ('NOT_UPHELD', 'Complaint not upheld'), ('PARTIALLY_UPHELD', 'Complaint partially upheld'), ('ADMINISTRATIVE_REMEDY', 'Administrative remedy required')], max_length=28)),
                ('remedy', models.TextField()),
                ('determined_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_complaint_determinations', to='staff.staffprofile')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='determinations', to='complaints.complaint')),
                ('determined_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_determinations', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('RECEIVED', 'Complaint received'), ('ACKNOWLEDGED', 'Acknowledged'), ('CLASSIFIED', 'Classified'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('INQUIRY_OPENED', 'Inquiry opened'), ('DETERMINED', 'Determination recorded'), ('COMMUNICATED', 'Outcome communicated'), ('ESCALATED', 'Escalated'), ('WITHDRAWN', 'Withdrawn'), ('REFERRED_OUT', 'Referred out'), ('TYPE_A_HANDOFF', 'Transferred to conduct')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor_name', models.CharField(blank=True, max_length=160)),
                ('detail', models.CharField(max_length=700)),
                ('previous_status', models.CharField(blank=True, max_length=24)),
                ('resulting_status', models.CharField(blank=True, max_length=24)),
                ('automatic', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaint_events', to='staff.staffprofile')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='complaints.complaint')),
            ],
            options={
                'ordering': ['occurred_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('requested_action', models.CharField(blank=True, max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='complaints.complaint')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_complaint_inquiries', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FileRecallOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(max_length=240)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('directive', models.TextField()),
                ('response_due_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recall_orders', to='cases.casereference')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recall_orders', to='complaints.complaint')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_recall_orders', to='staff.staffprofile')),
                ('target_custodian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_recall_orders', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(max_length=240)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_links', to='complaints.complaint')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_links', to='documents.document')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_complaint_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('complaint', 'document'), name='unique_complaint_document_link')],
            },
        ),
    ]
