# Generated by Django 5.2.8 on 2026-08-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintevent',
            name='event_type',
            field=models.CharField(choices=[('RECEIVED', 'Complaint received'), ('ACKNOWLEDGED', 'Acknowledged'), ('CLASSIFIED', 'Classified'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('INQUIRY_OPENED', 'Inquiry opened'), ('DETERMINED', 'Determination recorded'), ('COMMUNICATED', 'Outcome communicated'), ('ESCALATED', 'Escalated'), ('WITHDRAWN', 'Withdrawn'), ('REFERRED_OUT', 'Referred out'), ('TYPE_A_HANDOFF', 'Transferred to conduct'), ('COMMENT', 'Comment added')], max_length=20),
        ),
    ]
