# Generated by Django 5.2.8 on 2026-08-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaintevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complainant_nin',
            field=models.CharField(blank=True, max_length=14, verbose_name='Complainant NIN'),
        ),
    ]
