# Generated by Django 5.2.8 on 2026-08-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_complainant_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='stakeholder_role',
            field=models.CharField(blank=True, choices=[('COMPLAINANT', 'Victim / complainant'), ('ACCUSED', 'Accused / defendant'), ('NEXT_OF_KIN', 'Next of kin'), ('WITNESS', 'Witness / informant'), ('COUNSEL', 'Legal representative')], max_length=16),
        ),
    ]
